#executar -> docker-compose up --build
version: '3'

services:
  normativasdb:
    image: postgres:10.1-alpine
    networks:
      - webnet
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
  normativasapp:
    build: .
    command:
      - ./wait-for-postgres.sh
      - ./wait-for-elasticsearch.sh
      - ./app-entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - normativasdb
      - normativaselasticsearch
      - normativasweb
    networks:
      - webnet
    volumes:
      - backupdata:/backup
      - ./:/app
      - uploaddata:/app/storage/app/public/uploads
      - logappdata:/app/storage/logs

  normativaselasticsearch:
    build: ./elasticsearch
    #restart: always
    environment:
      - discovery.type=single-node
      - "cluster.name=normativas"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=normativaselasticsearch"    
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - webnet
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - backupdata:/backup
  normativasweb:
    image: nginx:latest
    ports:
      - ${PORT_TO_EXPOSE}:80
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - normativasphp
    networks:
      - webnet
  normativasphp:
    build: ./php
    #    image: php:7.2-fpm
    volumes:
      - ./:/app
      - uploaddata:/app/storage/app/public/uploads
      - logappdata:/app/storage/logs
    networks:
      - webnet

networks:
  webnet:

volumes:
  esdata1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ELASTIC_DATA_FOLDER}
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_DATA_FOLDER}
  uploaddata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${UPLOAD_FOLDER}
  logappdata:
    driver: local
  backupdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DUMP_OUTPUT_FOLDER}

